In [1]:
def fibonacci(n):
    if n<=1:
        return 1
    else:
        return n+fibonacci(n-1)
fibonacci(10)

55

In [2]:
fibonacci(1)

1

In [3]:
fibonacci(100)

5050

In [4]:
#les structure de données 

In [5]:
liste_1=[1,8,5,10,56,2,5]

In [6]:
liste_2=["Ouaga","Bobo", "koudougou"]

In [7]:
import pandas as pd

In [8]:
liste_3=[]
liste_4=[liste_1,liste_2]

In [9]:
#un tuple c'est comme une liste qu'on ne peut pas modifier utiliser très rarement


In [10]:
tuple_1=(1,2,4,8)

In [11]:
#string chaine de carctère

In [12]:
#Une séquence est une ensemble d'élement ordonnées

In [13]:
prenom="Adama"

In [14]:
# dans une liste chaque élement a un index

In [15]:
# liste_1[0] contient le premier element de la liste_1

In [16]:
#liste_1[-1] contient le dernier element de la liste_1

In [17]:
# liste_1 liste_2

In [18]:
liste=["adama","dems","lapoe","edeper"]

In [19]:
liste[-1]

'edeper'

In [20]:
liste[0]

'adama'

In [21]:
liste[-2]

'lapoe'

In [22]:
#liste[debut: fin :pas] comme au niveau de range(debut:fin:pas)

In [23]:
liste[0:2:2]

['adama']

In [24]:
liste[0:3:2]

['adama', 'lapoe']

In [25]:
print(liste)

['adama', 'dems', 'lapoe', 'edeper']


In [26]:
# avoir une liste renversé avec linste[::-1]

In [27]:
print(liste[::-1])

['edeper', 'lapoe', 'dems', 'adama']


In [28]:
print(liste[::2])

['adama', 'lapoe']


In [29]:
print(liste[2:])

['lapoe', 'edeper']


In [30]:
print(liste[:3])# pour afficher les premier n element d'une liste print(liste[:n])

['adama', 'dems', 'lapoe']


In [31]:
liste[0]="damso"# modificagion d'un élément d'une liste à travers l'index

In [32]:
print(liste) 

['damso', 'dems', 'lapoe', 'edeper']


In [33]:
# different méthode que l'on peut realiser sur une liste

In [34]:
liste.append('adama') # append c'est pour ajouter un element à la fin d'une liste

In [35]:
liste

['damso', 'dems', 'lapoe', 'edeper', 'adama']

In [36]:
liste.insert(1,'issa') # insert permet d'inserser un element à un index passé en paramètre

In [37]:
liste

['damso', 'issa', 'dems', 'lapoe', 'edeper', 'adama']

In [38]:
# pour ajouter une liste à une liste on utilise la fonction extend

In [39]:
liste_5=['daouda','yacouba', 'mahamady','abasse']

In [40]:
liste_5

['daouda', 'yacouba', 'mahamady', 'abasse']

In [41]:
print(liste_5)

['daouda', 'yacouba', 'mahamady', 'abasse']


In [42]:
# on veut ajouteer liste_5 à list

In [43]:
liste.extend(liste_5)

In [44]:
liste

['damso',
 'issa',
 'dems',
 'lapoe',
 'edeper',
 'adama',
 'daouda',
 'yacouba',
 'mahamady',
 'abasse']

In [45]:
len(liste)# pour determiner le nombre d'element d'une liste

10

In [46]:
# trie c'est fait avec la fonction sort

In [47]:
liste.sort()

In [48]:
liste

['abasse',
 'adama',
 'damso',
 'daouda',
 'dems',
 'edeper',
 'issa',
 'lapoe',
 'mahamady',
 'yacouba']

In [49]:
#compter l'ocurrence d'un element dans une liste

In [50]:
liste.count('adama')

1

In [51]:
#pip install rembg

### from rembg import remove
## from PIL import Image
## input_path='image.jpg'
### output_path='image.png'
# inp=Image.open(input_path)
# output=remove(inp)
# output.save(output_path)

In [52]:
# installation de rembg

In [53]:
if 'adama' in liste:
    print('oui')
else:
    print('Non')

oui


In [54]:
if 'paris' in liste:
    print('oui')
else:
    print('Non')

Non


In [55]:
for i in liste:
    print(i)

abasse
adama
damso
daouda
dems
edeper
issa
lapoe
mahamady
yacouba


In [56]:
for i , valeur in enumerate(liste):
    print(i,valeur)

0 abasse
1 adama
2 damso
3 daouda
4 dems
5 edeper
6 issa
7 lapoe
8 mahamady
9 yacouba


In [57]:
for i,j in zip(liste, liste_1):
    print(i,j)

abasse 1
adama 8
damso 5
daouda 10
dems 56
edeper 2
issa 5


In [58]:
def fibonacci(n): 
    a=0
    liste=[]
    b=1 
    while a<=n:
        liste.append(a)
        a,b=b,a+b
    print(liste)

In [59]:
fibonacci(1000)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]


In [60]:
# un dictionnaire est une structure de données dont les elements ne sont pas ordonnés

In [61]:
dictionnaire_1={
    "chien":"dog",
    "chat":"cat",
    "souris":"mouse",
    "oiseau":"bird"
    # on ne ppeut pas avoir deux o2 clé du même dans un cictionnaire
}

In [62]:
inventaire={
    "bananes":155454,
    "oissons":1454,
    "nano":45,
    "chien":4598
}
# un dictionnaire qui contient des dictionnaires
dictionnaire_2={
    "dict_1":dictionnaire_1,
    "dict_2":inventaire
}

In [63]:
# les operations de base qu'on peut faire sur les dictionnaires

In [64]:
# pour afficicher les differentes valeurs de notre dict
inventaire.values()

dict_values([155454, 1454, 45, 4598])

In [65]:
#concernant l'affichage des clés on a
inventaire.keys()

dict_keys(['bananes', 'oissons', 'nano', 'chien'])

In [66]:
len(inventaire)

4

In [67]:
# ajout d'une associations dans notre dicitionnaire
inventaire["dolo"]=1523

In [68]:
# get permet de chercher une valeur associée à une cle dans un dictionnaire
print(inventaire.get('45'))

None


In [69]:
# on peut egalement ajouter une valeur de retour par defaut au cas ou l'on ne trouve pa l'element
inventaire.get('client',1)

1

In [70]:
inventaire.get('dame',"rien du tout")

'rien du tout'

In [71]:
# fromkeys permet de generer des valeurs pour des clé dun dictionnaire
inventaire.fromkeys(liste_1)

{1: None, 8: None, 5: None, 10: None, 56: None, 2: None}

In [72]:
inventaire.fromkeys(liste_1,"defaut")

{1: 'defaut',
 8: 'defaut',
 5: 'defaut',
 10: 'defaut',
 56: 'defaut',
 2: 'defaut'}

In [73]:
# retirer une association 
# de le recuperer dans une valeur 
a=inventaire.pop('bananes')

In [74]:
print(a)

155454


In [75]:
# pour juste imprimer les clé
for i in inventaire:
    print(i)

oissons
nano
chien
dolo


In [76]:
inventaire

{'oissons': 1454, 'nano': 45, 'chien': 4598, 'dolo': 1523}

In [77]:
for i in inventaire.values():
    print(i)

1454
45
4598
1523


In [78]:
# affichage de 
for i,y in inventaire.items():
    print(i,y)

oissons 1454
nano 45
chien 4598
dolo 1523


In [79]:
classeur={
    "positif":[],
    "negatif":[]
}

In [80]:
def trier(classeur,nombre):
    if nombre<0:
        classeur["negatif"].append(nombre)
    else:
        classeur["positif"].append(nombre)
    return classeur

In [81]:
trier(classeur,5)

{'positif': [5], 'negatif': []}

In [82]:
trier(classeur,41)

{'positif': [5, 41], 'negatif': []}

In [83]:
classeur

{'positif': [5, 41], 'negatif': []}

In [84]:
trier(classeur,-1)

{'positif': [5, 41], 'negatif': [-1]}

In [85]:
import time
start=time.time()
listet=[]
for i in range(10):
    listet.append(i**2)
print(listet)
end=time.time()
print(end-start)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
0.0


In [86]:
# comprenhension des listes
start=time.time()
listed=[i**2 for i in range(10)]
print(listed)
end=time.time()
print(end-start)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
0.0010051727294921875


In [87]:
# utilisation des comprenhence
#1. reduction de nombres de lignes
#2. ca fait plus python professionnel
#3. le processus est assez 

In [88]:
# une Nested List c'est une liste qui contient des listes
liste_Nested=[[i for i in range(3)]for j in range(4)]
liste_Nested

[[0, 1, 2], [0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [89]:
dictionnaire={
    '0':'Pierre',
    '1':'Jean',
    '2':'Julie',
    '3':'Sophie'
}

In [90]:
# creation de dictionnaire avec la comprehension des listes
prenoms=['Pierre','Jean','Julie','Sophie']

In [91]:
dico={k:v for k,v in enumerate(prenoms)}
print(dico)

{0: 'Pierre', 1: 'Jean', 2: 'Julie', 3: 'Sophie'}


In [92]:
dico.keys()

dict_keys([0, 1, 2, 3])

In [93]:
dico.values()

dict_values(['Pierre', 'Jean', 'Julie', 'Sophie'])

In [94]:
ages=[25,18,18,23]

In [95]:
dico_2={prenom:age for prenom,age in zip(prenoms,ages) if age >23}
# la condition a été utilisée pour selectionner une parti des ages

In [96]:
dico_2

{'Pierre': 25}

## Tuple comprehension

In [97]:
tuple_1=(i**2 for i in range(10))
tuple_1

<generator object <genexpr> at 0x0000020016D71820>

### un peut nous voiyons qu'on arrive pas à creer un tuple mais plutot un generator

In [98]:
# ajoutons tous simple des parenthèses au niveau du generator pour avoir de vrais tuple
tuple_1=tuple((i**2 for i in range(10)))
tuple_1

(0, 1, 4, 9, 16, 25, 36, 49, 64, 81)

In [99]:
dico_exo={str(k):k**2 for k in range(0,20) }

## les fonctions de base que l'on trouve en python

  #### sites de la documentations officiel de python
  ###### docs/python.org/3/library/function.html#len

In [100]:
abs(-5)

5

In [101]:
import math

In [102]:
math.sqrt(4)

2.0

In [103]:
math.sin(60)

-0.3048106211022167

In [104]:
math.sin(math.pi/2)

1.0

In [105]:
a=0.874464544

In [106]:
round(a,2)

0.87

In [107]:
type(21)

int

In [108]:
x=25
adam=str(x)

In [109]:
type(adam)

str

In [110]:
y='20'

In [111]:
y=int(y)

In [112]:
float(y)

20.0

In [113]:
type(y)

int

In [114]:
liste_8=[0,54,54,85,5]
typetuple=tuple(liste_8)

In [115]:
typetuple

(0, 54, 54, 85, 5)

In [116]:
liste_9=list(typetuple)

In [117]:
liste_9

[0, 54, 54, 85, 5]

In [118]:
bin(15)

'0b1111'

In [119]:
bin(2)

'0b10'

In [120]:
bin(16)

'0b10000'

 ### utilisation de la fonction format

In [121]:
x=19
ville="Ouagadougou"
print("Il fait {} degé C à {}".format(x,ville))

Il fait 19 degé C à Ouagadougou


In [122]:
import numpy as np

parametres={
    "W1":np.random.randn(2,4),
    "b1":np.zeros((2,1)),
    "W2":np.random.randn(2,2),
    "b2":np.zeros((2,1))
}

In [123]:
for i in range(1,3):
    print("couche ",i)
    print(parametres["W{}".format(i)])

couche  1
[[-0.40022468 -0.37656008  0.98152113 -0.31363122]
 [-0.92550007 -0.98561466  1.33002555 -0.7587076 ]]
couche  2
[[-1.19584524  0.33770938]
 [ 0.16680853 -2.11647971]]


#### Une autre façon d'obtenir ce resultat

In [124]:
for i in range(1,3):
    print("couche ",i)
    print(parametres["W"+str(i)])

couche  1
[[-0.40022468 -0.37656008  0.98152113 -0.31363122]
 [-0.92550007 -0.98561466  1.33002555 -0.7587076 ]]
couche  2
[[-1.19584524  0.33770938]
 [ 0.16680853 -2.11647971]]


### utilisation de la fonction open avec ses mode

In [125]:
f=open("fichier.txt",'w')

In [126]:
f.write("je suis bonjour")

15

In [127]:
f.close()

In [128]:
f=open("fichier.txt",'r')
print(f.read())
f.close()

je suis bonjour


#### autrement et surtout efficacement

In [2]:
with open("fichier.txt",'w') as f:
    for i in range(10):
        f.write("{}^2 ={}\n".format(i,i**2))

In [5]:
with open("fichier.txt",'r') as f:
    liste=f.read().splitlines()
liste

['0^2 =0',
 '1^2 =1',
 '2^2 =4',
 '3^2 =9',
 '4^2 =16',
 '5^2 =25',
 '6^2 =36',
 '7^2 =49',
 '8^2 =64',
 '9^2 =81']

liste52=[]
with open('fichier.txt','r') as f:
    print(f.read())

In [131]:
import numpy as np

In [132]:
import matplotlib.pyplot as plt