In [1]:
print(" Adama")

 Adama


### Programmation en utilisant juste des virgule pour la concatenation

In [2]:

age=25
nom="Adama"
print("vous vous appelez ",nom, " vous avez ", age, "ans")
print("Vous vous appelez "+nom+" vous avez "+str(age)+" ans ")

vous vous appelez  Adama  vous avez  25 ans
Vous vous appelez Adama vous avez 25 ans 


In [3]:
print('adama')

adama


# Numpy

### l'attribut shape de numpy donne l'information sur la table à laquelle nous étudions

In [10]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a.ndim

1

In [ ]:
a.shape

(3,)

#### size et shape sont les plus importants en machine learning et en data science

##### zeros initialise notre tableau ndrray avec des 0

In [ ]:
B=np.zeros([2,4,5])

In [ ]:
B

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
B.shape

(2, 4, 5)

In [ ]:
type(B.shape)

tuple

In [ ]:
B.size

40

In [ ]:
a=np.full((2,3),1)

In [ ]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
n=np.random.BitGenerator((3,2))

NameError: name 'np' is not defined

In [ ]:
a=[1,2,3,4,6]
y=a
y[2]=7
print(a)

[1, 2, 7, 4, 6]
