##### L'univers peut être modeliser avec 03 notion avec la poo

###### des objet(nom) qui peuvent être qualifier par des attribut() et des actions ou methodes (verbe)
###### at

In [24]:
  import numpy as np

In [25]:
arr_1d=np.array([1,2,3,4])

In [26]:
arr_1d.sum()

10

In [27]:
arr_1d.mean()

2.5

In [28]:
arr_1d.size

4

In [29]:
arr_1d.view()

array([1, 2, 3, 4])

In [30]:
arr_1d.shape

(4,)

In [31]:
arr_1d.dtype

dtype('int32')

In [32]:
arr_1d.ndim

1

In [33]:
tableau1=np.ones(3)

In [34]:
tableau1

array([1., 1., 1.])

In [35]:
tableau1=np.ones((3,3))

In [36]:
tableau1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Exercice numpy

In [37]:
def initialisation(m,n):
    tableau =np.random.randn()
    